### ISSUE TITLE
error in every connected glass

### ISSUE THREAD

**Issue by carmeops** [Faithful-Resource-Pack/Faithful-Java-64x#11]
all colors and clear versions of the connected glass textures are missing the border pixels at the bottom of the 42.png

**Comment by HARYA301** [comment]
Hey! Thank you for your report. I will take a look at this later.

**Comment by 3vorp** [comment]
fixed with https://github.com/Faithful-Resource-Pack/Faithful-Java-64x/commit/69d2e1f862fc27f867c89b2794d31af31a977c33
