### ISSUE TITLE
Glass Pane 1.20 Beta 9 Bug Report 

### ISSUE THREAD

**Issue by DynamicDylan** [Faithful-Resource-Pack/Faithful-Java-64x#19]
Glass Panes looking from the west and north positions reveal connected textures that are acting weird  
![2023-07-26_12 58 22](https://github.com/Faithful-Resource-Pack/Faithful-Java-64x/assets/21348461/1da0fc55-f8c3-42dc-8317-1948e370b378)
![2023-07-26_12 57 02](https://github.com/Faithful-Resource-Pack/Faithful-Java-64x/assets/21348461/2cb98c0c-06f1-4953-bacd-7a4c422ab464)

**Comment by Pomi108** [comment]
Most likely a bug with OptiFine. Check other resource packs that have glass pane CTM

**Comment by HARYA301** [comment]
I'm closing this one as it's a bug with Optifine.
