### ISSUE TITLE
Pig Texture messed up

### ISSUE THREAD

**Issue by HanDrax** [Faithful-Resource-Pack/Faithful-Java-64x#2]
My pig texture is messing up like this

![2021-08-10_10 42 07](https://user-images.githubusercontent.com/74276937/128805937-82f3f5d3-bcb7-45cd-9d69-e462cca4413e.png)
I don't know if the problem is just me or someone has it too?

**Comment by Juknum** [comment]
Can you tell us which version of Compliance you are using? thx.

**Comment by HaragOnMC** [comment]
Impossible to reproduce.
