### ISSUE TITLE
Nordic letters

### ISSUE THREAD

**Issue by el97** [Faithful-Resource-Pack/Faithful-Java-64x#20]
Nordic letters such as åäö does not have the same style as the rest of the alphabet. 
![Missing texture for åäö](https://github.com/Faithful-Resource-Pack/Faithful-Java-64x/assets/23169868/eeca4e05-d74a-46ba-92d8-9e9dbf0902ee)

**Comment by el97** [comment]
I see. Thanks for the quick reply!

**Comment by el97** [comment]
I have looked in the repo and I found the font directory, which I guess is the one that shows the letters. If I want to contribute with the nordic letters, how do I do that?

**Comment by Pomi108** [comment]
Join our [Discord server](https://discord.gg/sN9YRQbBv7) and read the [Contributor's Handbook](https://docs.faithfulpack.net/pages/textures/contributor-handbook) for details on how to contribute
