### ISSUE TITLE
Armor trims not updated 1.20 Beta 9 Bug

### ISSUE THREAD

**Issue by NoFaceGameDev** [Faithful-Resource-Pack/Faithful-Java-64x#21]
Armor trims haven't been updated in the release of 64x 1.20 beta 9.
![image](https://github.com/Faithful-Resource-Pack/Faithful-Java-64x/assets/132075372/5d1d8357-480a-4b13-8126-2798ed1aaad5)

**Comment by RobertRR11** [comment]
the resource pack is not finished
