### ISSUE TITLE
Infinity symbol is missing

### ISSUE THREAD

**Issue by SpomJ** [Faithful-Resource-Pack/Faithful-Java-64x#24]
I dont actually know where to submit these things, so i'm going to put it here.

![20231124_12h31m01s_grim](https://github.com/Faithful-Resource-Pack/Faithful-Java-64x/assets/75751809/49764cb6-9ad9-4661-8d8e-965bb15770c6)

**Comment by 3vorp** [comment]
The extended font set hasn't been done yet since it requires a lot of extensive cross-referencing and is generally a pain. This is planned for the future but probably won't be done anytime soon.
