### ISSUE TITLE
Cod texture has a lot of z-fighting

### ISSUE THREAD

**Issue by Lolothepro** [Faithful-Resource-Pack/Faithful-Java-64x#25]
https://github.com/Faithful-Resource-Pack/Faithful-Java-64x/assets/68275908/2983d5e7-1513-46fa-9c9f-3acf927167fe

**Comment by DMgaming100** [comment]
would be fixed next update

**Comment by 3vorp** [comment]
for the time being, you can use whatever version you need to from here: https://database.faithfulpack.net/packs/64x-Java/Experimental/

this has the latest changes including the fix
