### ISSUE TITLE
1.16 missing textures

### ISSUE THREAD

**Issue by mvadovszki** [Faithful-Resource-Pack/Faithful-Java-64x#3]
this is for the latest 1.16 version - 'Compliance 64x - Parity Update'

missing texture for 'double chest', clay, oak/spruce/birch trapdoor, birth/jungle/warped door

edit: didn't realize at the time I could just use the 1.17.1 version in 1.16.5

for the latest 1.17.1 - 'A8'
only the warped door texture is missing, from this list

**Comment by Pomi108** [comment]
The resource pack is not finished. Of course there are missing textures.
