### ISSUE TITLE
Chest Z-fighting on 1.18 beta

### ISSUE THREAD

**Issue by Epicjii** [Faithful-Resource-Pack/Faithful-Java-64x#4]
![2021-12-23_01 18 35](https://user-images.githubusercontent.com/66448504/147173119-f5a4f677-b96f-4ea6-b80d-8e17de0d164a.png)

Hopefully this shows what I am talking about

I am also using latest version of Optifine.

**Comment by Juknum** [comment]
@Epicjii sorry for the late response, is it still happening on the latest version?

**Comment by Epicjii** [comment]
No I think you guys fixed it in the immediate update after I created the issue.
