### ISSUE TITLE
Add 1.18.2 to supported versions

### ISSUE THREAD

**Issue by waddon1** [Faithful-Resource-Pack/Faithful-Java-64x#6]
I can't use this resource pack in my modpack as it does not have the 1.18.2 tag

**Comment by Juknum** [comment]
There is actually no mods/modpacks support for Faithful 64x, what are you trying to do?

**Comment by waddon1** [comment]
On curseforge it needs the 1.18.2 tag on the latest file upload, so it can be used in 1.18.2 modpacks.
![image](https://user-images.githubusercontent.com/14033361/163280501-7b8bf8bb-3855-4a26-84ef-eeae269bbddf.png)

**Comment by Juknum** [comment]
Oh then it's an issue with the curseforge of faithful 64x ?

**Comment by Juknum** [comment]
@HaragOnMC I hope you will see this, could you add 1.18.2 as a supported version for the latest beta of Faithful x64?
