### ISSUE TITLE
Texture bug in Creative inventory

### ISSUE THREAD

**Issue by Aditoo17** [Faithful-Resource-Pack/Faithful-Java-64x#7]
In the Creative inventory UI, the active tab texture does not line up with the texture of the main box. See the active Redstone tab in the picture.

![faithful_x64_bug](https://user-images.githubusercontent.com/42938951/170086175-afb66f21-9a3c-436c-9a57-0acc215c5eed.png)

**Comment by HaragOnMC** [comment]
This problem is due to a bug with the texture. I've alread told the artist but any fix was sent.
I will look into a future fix soon.

**Comment by Pomi108** [comment]
This has now been fixed and the fix will be released with the next public version.
