### ISSUE TITLE
Conduit wind is broken

### ISSUE THREAD

**Issue by Aditoo17** [Faithful-Resource-Pack/Faithful-Java-64x#8]
The "wind" that appears around the conduit has a broken animation. Instead of smoothly flowing, it flashes for a frame, then disappears. Here is a video.

https://user-images.githubusercontent.com/42938951/175343503-f3b2fb6a-ae9f-4ec4-bf6c-e810f7c613b0.mp4

**Comment by Juknum** [comment]
@Aditoo17 sorry for the late response, is it still happening? can you show us the same textures with Vanilla?

**Comment by Aditoo17** [comment]
Here is a video of a conduit in both Faithful 64x and Vanilla. As you can see, the "wind" is supposed to flow smoothly around the conduit, but in Faithful 64x, it simply occasionally flashes, then disappears. This is still happening as of now.

https://user-images.githubusercontent.com/42938951/183247248-fd2f14d6-57a2-43b4-b5f4-24fd201b2471.mp4

**Comment by 3vorp** [comment]
submitted a fix, will get back to you in the next 3-4 days to see if it passed or not

**Comment by 3vorp** [comment]
should be fixed with https://github.com/Faithful-Resource-Pack/Faithful-Java-64x/commit/73e3d9256da412085644590025d9dfd733b5c625
