### ISSUE TITLE
Glow item frame block texture is incorrect

### ISSUE THREAD

**Issue by omega9380** [Faithful-Resource-Pack/Faithful-Java-64x#9]
The glow item frame block texture is incorrect.  It looks like what happened is the "glow item frame" _item_ texture was copied into the _block_ texture instead of using a separate (but identically named) block texture.

![glowframebug](https://user-images.githubusercontent.com/13081643/182189473-c24971a7-f973-4cca-8cc3-5a41aa5423ec.png)
e

**Comment by HaragOnMC** [comment]
Hey! Please redownload Faithful 64x, I just fixed the bug :)
Have fun using Faithful 64x!
